# Generates the repo-root .clangd so the clangd language server parses CERF
# with the SAME flags msbuild uses. Without it clangd falls back to a bare
# `clang <file>` invocation (no vcpkg includes, no MSVC STL, no -std=c++20)
# and floods every TU with phantom errors (can't find <span>/<optional>/
# nlohmann/json.hpp, "inline variables are a C++17 extension", ...).
#
# .clangd carries an ABSOLUTE vcpkg include path (clangd resolves a relative
# -I against each TU's own directory, which breaks for nested sources), so it
# is machine-specific and gitignored -- this generator reproduces it on any
# checkout. build.ps1 runs it on every build.

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

# Triplet is pinned in cerf/cerf.vcxproj (<VcpkgTriplet>x86-windows-static).
# msbuild manifest mode installs to vcpkg_installed/<triplet>/<triplet>/include.
$vcpkgInc = Join-Path $root "vcpkg_installed\x86-windows-static\x86-windows-static\include"
if (-not (Test-Path $vcpkgInc)) {
    Write-Host "[clangd] note: vcpkg include dir not present yet ($vcpkgInc)."
    Write-Host "[clangd]       It appears after the first msbuild restore; .clangd still written."
}
# clangd YAML is happier with forward slashes; backslashes risk being read as escapes.
$incFwd = $vcpkgInc -replace '\\', '/'

# Flags mirror cerf/cerf.vcxproj's ClCompile (Release/dev defaults):
#   LanguageStandard=stdcpp20, ConformanceMode=true (/permissive-),
#   CharacterSet=Unicode, _CONSOLE, NDEBUG, CERF_DEV_MODE=1 (dev build).
# clang-cl driver => MSVC STL + Windows SDK auto-detected (no hardcoded paths).
# i686 target => matches the Win32 (32-bit) build, not clangd's x86_64 default.
$lines = @(
    "# AUTO-GENERATED by tools/gen_clangd.ps1 -- do not edit; regenerated on every build."
    "# Makes clangd parse CERF with the same flags as the msbuild (cerf.vcxproj) build."
    "CompileFlags:"
    "  Compiler: clang-cl"
    "  Add:"
    '    - "--target=i686-pc-windows-msvc"'
    '    - "/std:c++20"'
    '    - "/EHsc"'
    '    - "/permissive-"'
    '    - "-DWIN32"'
    '    - "-D_CONSOLE"'
    '    - "-DNDEBUG"'
    '    - "-DUNICODE"'
    '    - "-D_UNICODE"'
    '    - "-DCERF_DEV_MODE=1"'
    "    - `"-I$incFwd`""
)
$dest = Join-Path $root ".clangd"
Set-Content -Path $dest -Value ($lines -join "`n") -Encoding utf8 -NoNewline
Write-Host "[clangd] wrote $dest (vcpkg include: $vcpkgInc)"
